"""empty message

Revision ID: 674c4565f9fe
Revises: 4444f116eaf5
Create Date: 2016-01-14 13:38:14.541000

"""

# revision identifiers, used by Alembic.
revision = '674c4565f9fe'
down_revision = '4444f116eaf5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('slug', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'slug')
    ### end Alembic commands ###
